### ISSUE TITLE
Plantage côté admin

### ISSUE THREAD

**Issue by TulipVorlax** [te2dy/odyssey#28]
Depuis que je suis passé à la toute dernière version de DotClear, j'ai un message d'erreur qui s'affiche côté admin et la seule possibilité est de se connecter en mode de secour (sans échec).
Il m'a fallut plusieurs semaines pour me rendre compte que le problème vient du thème Origine Mini et je trouve cela bien triste car j'aime beaucoup ce thème que j'ai découvert il y a quelques mois.

Le message d'erreur est le suivant :

503 : Site temporarily unavailable
Call to a member function moduleInfo() on null

**Comment by te2dy** [comment]
C'est vrai que la 2.28 de Dorclear a chamboulé pas mal de choses.

Je suis en train de développer une nouvelle version de ce thème (qui sera renommé Odyssée) qui sera compatible avec la 2.28.

Je vous préviens dès que je mets une version disponible au téléchargement.

**Comment by TulipVorlax** [comment]
Merci beaucoup.

En attendant, je sais pas quoi utiliser comme thème. Quand je vois dans les détails des thèmes sur DotAddict que la majorité n'ont pas été mis à jour depuis des années... J'ai parfois songé à remplacer DotClear par Wordpress, mais je n'utilise déjà pas toutes les fonctions du premier...

**Comment by te2dy** [comment]
Vous pouvez essayer de télécharger les fichiers de la branche Dotclear-2.28 que je suis en train de développer. Il manque pas mal d'options dans l'administration mais le thème devrait être fonctionnel. 😉 À voir ici : 
https://github.com/te2dy/odyssey/tree/Dotclear-2.28

**Comment by te2dy** [comment]
Vous pouvez télécharger le thème sur cette page : https://github.com/te2dy/odyssey/releases/tag/0.5-alpha

**Comment by TulipVorlax** [comment]
Je viens de tester. J'ai copié l'adresse web du ZIP et j'ai installé ça sur un blogue de test et quelques minutes plus tard sur mon vrai blogue. Ça fonctionne.
Il manque en effet quelques options que j'utilisais. L'affichage du résumé sur la liste des articles, par exemple. Mais ce n'est pas grâve, prenez votre temps.
Bonne année !

**Comment by te2dy** [comment]
La thème a été publié sur [DotAddict](https://themes.dotaddict.org/galerie-dc2/details/odyssey). Vous devriez recevoir des mises à jour directement depuis votre interface d’administration.

J’ajouterai prochainement l’option qui permet d’avoir un extrait dans la liste des billets.
